- hosts: node-redis-1
  sudo: yes

  vars_files:
    - ./vars/base-env.yml

  vars:
    - foo: "bar"

    - multiline: |
        test1
        test2
  roles:
    - common
    - redis

- hosts: node-redis-2
  sudo: yes

  vars_files:
    - ./vars/base-env.yml

  vars:
    - foo: "bar"

    - multiline: |
        test1
        test2
  roles:
    - common
    - redis
